### ISSUE TITLE
Allow devServerTarget for different Angular run configurations

### ISSUE THREAD

**Issue by xxluke** [playwright-community/playwright-ng-schematics#7]
At the moment, when using `ng e2e`, Angular is always started by using the `webServer.command` in `playwright.config.ts`, which by default is `npm run start`.

It would be better if it would use the `devServerTarget` property in `angular.json` to start that app and by that also allow different configurations. baseUrl can (should) also be set based on the devServerTarget. That's also how Protractor, Cypress and ngx-playwright/test handle it.

Usage example:
angular.json:
```json
        "e2e": {
          "builder": "playwright-ng-schematics:playwright",
          "options": {
            "devServerTarget": "my-app:serve",
            "ui": true
          },
          "configurations": {
            "production": {
              "devServerTarget": "my-app:serve:production"
            }
          }
        }
```
Commands in this case: `ng e2e` or `ng e2e -c production`

Use case:

You might have different Angular settings for the app, for example one that uses a local backend and one that uses a proxy for the production backend. Or you want to run the tests on the production build in the CI pipeline but a dev build locally.

It's probably possible to copy a lot from the Cypress implementation: https://github.com/cypress-io/cypress/blob/develop/npm/cypress-schematic/src/builders/cypress/index.ts#L49

**Comment by jfgreffier** [comment]
Thanks for the clear issue.

It is available in 1.1.0

Let me know how it goes, and if the docs are clear

**Comment by xxluke** [comment]
Thank you for the quick response. I was able to test the new version today. There are two new issues, unfortunately:
### 1.
env variables aren't passed through to playwright anymore.

### 2.
I got this error:
```
X [ERROR] The build was canceled

X [ERROR] Terminating worker thread [plugin angular-vite-optimize-deps]

    node_modules/piscina/dist/index.js:428:26:
      428 │             taskInfo.done(new Error('Terminating worker thread'));
          ╵                           ^

    at ThreadPool.destroy (C:\development\my-app\node_modules\piscina\dist\index.js:428:27)
    at Piscina.destroy (C:\development\my-app\node_modules\piscina\dist\index.js:631:65)
    at JavaScriptTransformer.close (C:\development\my-app\node_modules\@angular\build\src\tools\esbuild\javascript-transformer.js:139:40)
    at C:\development\my-app\node_modules\@angular\build\src\builders\dev-server\vite-server.js:116:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)

  This error came from the "onLoad" callback registered here:

    node_modules/@angular/build/src/builders/dev-server/vite-server.js:501:22:
      501 │                 build.onLoad({ filter: /\.[cm]?js$/ }, async (args) => {
          ╵                       ~~~~~~

    at setup (C:\development\my-app\node_modules\@angular\build\src\builders\dev-server\vite-server.js:501:23)
    at handlePlugins (C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:1150:21)
    at buildOrContextImpl (C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:873:5)
    at Object.buildOrContext (C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:699:5)
    at C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:2032:68
    at new Promise (<anonymous>)
    at Object.context (C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:2032:27)
    at Object.context (C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:1874:58)
    at prepareEsbuildOptimizerRun (file:///C:/development/my-app/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:50792:33)
```
I have no idea what that means. The normal serve/build works fine. I'm using Windows.

**Comment by jfgreffier** [comment]
for 1. my bad, I forgot to pass along process.env

I created a new issue for 2.
