### ISSUE TITLE
Build issue 'Terminating worker thread'

### ISSUE THREAD

**Issue by jfgreffier** [playwright-community/playwright-ng-schematics#8]
I got this error:
```
X [ERROR] The build was canceled

X [ERROR] Terminating worker thread [plugin angular-vite-optimize-deps]

    node_modules/piscina/dist/index.js:428:26:
      428 │             taskInfo.done(new Error('Terminating worker thread'));
          ╵                           ^

    at ThreadPool.destroy (C:\development\my-app\node_modules\piscina\dist\index.js:428:27)
    at Piscina.destroy (C:\development\my-app\node_modules\piscina\dist\index.js:631:65)
    at JavaScriptTransformer.close (C:\development\my-app\node_modules\@angular\build\src\tools\esbuild\javascript-transformer.js:139:40)
    at C:\development\my-app\node_modules\@angular\build\src\builders\dev-server\vite-server.js:116:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)

  This error came from the "onLoad" callback registered here:

    node_modules/@angular/build/src/builders/dev-server/vite-server.js:501:22:
      501 │                 build.onLoad({ filter: /\.[cm]?js$/ }, async (args) => {
          ╵                       ~~~~~~

    at setup (C:\development\my-app\node_modules\@angular\build\src\builders\dev-server\vite-server.js:501:23)
    at handlePlugins (C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:1150:21)
    at buildOrContextImpl (C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:873:5)
    at Object.buildOrContext (C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:699:5)
    at C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:2032:68
    at new Promise (<anonymous>)
    at Object.context (C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:2032:27)
    at Object.context (C:\development\my-app\node_modules\vite\node_modules\esbuild\lib\main.js:1874:58)
    at prepareEsbuildOptimizerRun (file:///C:/development/my-app/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:50792:33)
```
I have no idea what that means. The normal serve/build works fine. I'm using Windows. It seems it only appears when Vite hasn't optimized the the dependencies yet, which is reproducable when you delete the `.angular/cache/18.2.2/my-app-name` directory. The issue might have existed before.

_Originally posted by @xxluke in https://github.com/playwright-community/playwright-ng-schematics/issues/7#issuecomment-2431352009_

**Comment by jfgreffier** [comment]
@xxluke

It seems you are using Angular 18.2.2 

What builder do you use ? You can dump here your angular.json

**Comment by xxluke** [comment]
I guess one of the installed packages was just broken. I deleted `package-lock.json` and run `npm i` again, afterwards it went fine.
